export const ANALYSIS_LOCALES = ['ko','en','ja'];

export const ANALYSIS_DATA = {
  price: {
    subject: { label:'TARGET', value:15.0 },
    comps:[
      {id:'A',value:14.2,tags:{ko:['규모 유사','연식 열위','일부 공실'],en:['Similar scale','Older condition','Partial vacancy'],ja:['規模類似','築年数で劣位','一部空室']}},
      {id:'B',value:15.1,tags:{ko:['규모 유사','연식 우위','만실'],en:['Similar scale','Newer condition','Fully occupied'],ja:['規模類似','築年数で優位','満室']}},
      {id:'C',value:13.8,tags:{ko:['입지 한 단계 열위','상태 유사'],en:['Weaker location','Similar condition'],ja:['立地が一段劣位','状態類似']}},
    ],
  },
  income:{full:9600,vacancy:1200,current:8400,opex:1400,noi:7000,surfaceYield:6.4,adjustedYield:4.7},
  finance:{
    A:{loan:6,rate:5,interest:3000,equity:9},
    B:{loan:10,rate:7,interest:7000,equity:5},
  },
  tenancy:{occupied:4,vacant:1,keyRent:3600,share:43,months:14},
  building:{age:24,repairs:[{key:'roof',amount:2000},{key:'exterior',amount:1500},{key:'hvac',amount:1500}],total:5000},
};

export const ANALYSIS_SCENARIOS = {
  current:{id:'current',label:'CURRENT',rate:'0%p',vacancy:'0',cashNeed:0,A:4000,B:0,rateA:0,rateB:0,vacancyLoss:0},
  conservative:{id:'conservative',label:'CONSERVATIVE',rate:'+1%p',vacancy:'3',cashNeed:2000,A:2500,B:-1900,rateA:-600,rateB:-1000,vacancyLoss:-900},
  stress:{id:'stress',label:'STRONG STRESS',rate:'+2%p',vacancy:'6',cashNeed:5000,A:1000,B:-3800,rateA:-1200,rateB:-2000,vacancyLoss:-1800},
};

const commonMap = ['PRICE','INCOME','FINANCE','TENANCY','BUILDING','SURVIVAL'];
const finalMap = ['PRICE','NOI','FINANCE','TENANCY','BUILDING','SURVIVAL'];

export const ANALYSIS_COPY = {
  ko:{
    metaTitle:'건물 분석 방법 | 가격·수익·권리·건물·입지·운영 | FIX BUILDING',
    metaDescription:'가격·수익·권리·건물·입지·운영의 6가지 기준과 7가지 분석도구로 건물 한 채를 어떤 순서로 봐야 하는지 쉽게 익히는 FIX BUILDING 분석 가이드.',
    hero:{eyebrow:'02 · ANALYSIS',title:'건물은 무엇을,\n어떤 순서로 분석해야 할까요?',lead:'좋은 건물인지 먼저 묻지 않습니다. 가격이 왜 만들어졌고, 실제 얼마가 남으며, 어떤 조건에서 결과가 달라지는지를 순서대로 봅니다.',cta:'6가지 분석법 보기',note:'PRICE → INCOME → FINANCE → TENANCY → BUILDING → SURVIVAL'},
    map:{eyebrow:'ANALYSIS MAP',title:'한 건물을 여섯 방향에서 봅니다.',lead:'한 축의 숫자로 전체 결론을 대신하지 않습니다. 각 축에서 근거를 확인한 뒤 마지막에 조건을 연결합니다.',items:[
      ['PRICE','이 가격은 왜 이 가격인가?','비슷한 거래의 가격차이를 만든 조건을 확인합니다.'],
      ['INCOME','월세가 아니라 실제 얼마가 남는가?','공실과 운영비를 지나 남는 운영수익을 봅니다.'],
      ['FINANCE','빌릴 수 있는 돈과 감당할 수 있는 돈은 같은가?','금융비용과 남는 유동성을 함께 봅니다.'],
      ['TENANCY','지금의 임대수익이 계속 유지될 수 있는가?','수입 집중도와 계약 변화의 영향을 봅니다.'],
      ['BUILDING','숫자에 안 잡히는 건물 자체의 문제는 없는가?','상태를 수선비·활용성·가격 영향으로 번역합니다.'],
      ['SURVIVAL','상황이 나빠져도 계속 보유할 수 있는가?','조건이 틀렸을 때 현금흐름이 얼마나 흔들리는지 봅니다.'],
    ]},
    axis:{
      price:{num:'01',question:'이 가격은 왜 이 가격인가?',intro:'호가를 기준점으로 삼지 않습니다. 비슷한 거래의 가격차이를 만든 조건부터 확인합니다.',flow:'호가 → 비교가격 → 단위가격 → 조건차이 → 프리미엄 근거 → 수익구조 교차검증',rule:'가격을 평가하기 전에, 가격을 설명합니다.',verdict:'추가 장점이 없다면 가격 측면에서는 다소 불리합니다.',note:'처음 본 호가가 이후 판단의 기준점이 되지 않도록 비교 기준을 먼저 만듭니다.',button:'조건 비교',target:'대상 15.0억'},
      income:{num:'02',question:'월세가 아니라 실제 얼마가 남는가?',intro:'만실 임대료에서 공실과 소유자 부담 비용을 차례로 빼야 운영수익 구조가 보입니다.',flow:'만실수입 → 공실손실 → 현재실제수입 → 운영비 → 단순화 NOI',rule:'높은 월세보다, 공실과 비용을 지나 실제로 남는 구조를 봅니다.',verdict:'표면 6.4%보다 공실·운영비 반영 기준 약 4.7%로 수익 매력은 낮아집니다.',note:'높은 수익률이 실제로 남아서 높은지, 위험과 비용 때문에 높아 보이는지 구분합니다.',labels:['만실 기준','공실 반영','단순화 NOI(순영업소득)'],deduct:['공실손실 -1,200만','운영비 -1,400만']},
      finance:{num:'03',question:'빌릴 수 있는 돈과 감당할 수 있는 돈은 같은가?',intro:'대출한도만 보면 자기자본은 줄지만 금융비용과 금리 민감도는 가려질 수 있습니다.',flow:'대출액 → 금리 → 연 금융비용 → 자기자본 → 남는 유동성 → 금리민감도',rule:'대출한도를 보지 말고, 금융비용과 남는 유동성을 함께 봅니다.',verdict:'금융비용은 A가 유리하고 초기 유동성은 B가 유리합니다.',verdictA:'금융비용은 A가 유리합니다.',verdictB:'초기 유동성은 B가 유리합니다.',note:'실제 대출조건은 차주·담보·승인구조에 따라 달라집니다.',labels:{loan:'대출',equity:'자기자본',interest:'연 이자'}},
      tenancy:{num:'04',question:'지금의 임대수익은 계속 유지될 수 있는가?',intro:'현재 월세가 크더라도 한 임차인에 집중돼 있거나 계약만료가 몰려 있으면 수익구조는 쉽게 달라질 수 있습니다.',flow:'현재수입 → 수입집중도 → 계약만료 → 공실 → 재임대 → 시장임대료',rule:'현재 월세보다, 그 월세가 얼마나 오래 유지될 수 있는지를 봅니다.',verdict:'한 임차인의 변화가 전체 수입에 미치는 영향이 큽니다.',note:'현재 계약의 질과 퇴거 후 공간의 경쟁력을 따로 봅니다.',key:'핵심 임차인',vacant:'공실',timeline:'계약 잔여 14개월'},
      building:{num:'05',question:'숫자에 안 잡히는 건물 자체의 문제는 없는가?',intro:'건물의 오래됨 자체보다 어떤 비용이 언제 발생하고, 공간 활용과 임대에 어떤 제약을 만드는지가 중요합니다.',flow:'상태 → 예상수선 → 발생시점 → 활용성 → 구조적 제약 → 가격반영',rule:'건물의 단점을 찾는 데서 끝내지 않고, 비용·임대·가격에 어떻게 연결되는지 봅니다.',verdict:'단기 현금소요는 불리하지만 가격에 충분히 반영되면 일부 상쇄될 수 있습니다.',note:'권리·법적 사용가능성·계약조건은 별도 확인이 필요합니다.',pins:{roof:'ROOF',exterior:'EXTERIOR',hvac:'HVAC'},repair:'NEAR-TERM REPAIR'},
      survival:{num:'06',question:'상황이 나빠져도 계속 보유할 수 있는가?',intro:'좋은 시나리오보다 조건이 틀렸을 때 현금흐름과 유동성이 얼마나 흔들리는지 확인합니다.',flow:'현재 → 금리충격 → 공실충격 → 수선비 → 반복현금흐름 → 유동성',rule:'미래를 맞히려 하지 말고, 조건이 틀렸을 때 어디까지 버틸 수 있는지 계산합니다.',verdict:'선택한 시나리오에 따라 A/B의 현금흐름 대응력 차이가 명확해집니다.',note:'스트레스값은 예측이 아니라 교육용 민감도 시나리오입니다.',educationNote:'시나리오의 금리·공실기간·수선비는 분석방법을 설명하기 위한 교육용 가정이며 실제 시장의 기준값을 의미하지 않습니다.',scenarioLeads:{current:'현재 확인된 조건이 유지된다면',conservative:'조건이 조금 불리하게 움직인다면',stress:'여러 조건이 동시에 크게 나빠진다면'},repeated:'연 반복 현금흐름 · 단위 만원',rate:'RATE',vacancy:'VACANCY',cashNeed:'ONE-TIME CASH NEED',months:'개월',none:'추가 없음'},
    },
    case:{eyebrow:'FULL ANALYSIS CASE',title:'15억짜리 건물, 무엇부터 봐야 할까요?',lead:'처음에는 가격과 임대수익처럼 눈에 잘 보이는 숫자부터 보게 됩니다. 하지만 이 정보만으로는 아직 판단하지 않습니다.',prev:'PREV',next:'NEXT',start:'분석 시작',finish:'마지막 프레임',scenario:'선택 시나리오',steps:[
      {name:'CASE START',title:'15억짜리 건물, 무엇부터 봐야 할까요?',body:'처음에는 가격과 임대수익처럼 눈에 잘 보이는 숫자부터 보게 됩니다. 하지만 이 정보만으로는 아직 판단하지 않습니다.',support:'호가 15억 / 만실 기준 연 임대수입 9,600만 / 단순 표면수익률 6.4% / 준공 24년 / 공실 1곳',decision:'아직 판정하지 않습니다.',note:'이 건물을 PRICE부터 SURVIVAL까지 순서대로 분해해봅니다.'},
      {name:'BASELINE',title:'건물을 보기 전에 기준을 먼저 정합니다.',body:'좋아 보이는 물건에 맞춰 기준을 바꾸면 판단이 흔들립니다. 먼저 감당 가능한 자금과 남겨둘 현금을 정합니다.',support:'총 가용현금 11억 / 최소 보유현금 목표 1억 / 장기보유 전제',decision:'기준을 먼저 세운 상태입니다.',note:'매입대금에 얼마를 넣을 수 있는지보다, 매입 후 무엇이 남는지도 같이 봅니다.'},
      {name:'PRICE',title:'가격을 평가하기 전에, 가격을 설명합니다.',body:'호가가 싸거나 비싸 보인다는 느낌보다 비슷한 거래가 왜 다른 가격에 체결됐는지부터 봅니다.',support:'대상 15.0억 / A 14.2억 / B 15.1억 / C 13.8억',decision:'추가 장점이 확인되지 않는다면 가격 측면에서는 다소 불리합니다.',note:'비교가격과 현재 수익구조로 설명되는 가격이 크게 다르면 그 차이의 원인을 다시 확인합니다.'},
      {name:'INCOME',title:'월세가 아니라 실제 얼마가 남는지를 봅니다.',body:'만실 숫자에서 공실과 소유자 부담 운영비를 차례로 빼면 건물의 운영수익 구조가 보입니다.',support:'9,600만 → 8,400만 → 7,000만 / 6.4% → 약 4.7%',decision:'표면수익률보다 공실·운영비를 반영한 수익 매력은 낮아집니다.',note:'7,000만은 이 사례에서 공실과 소유자 부담 운영비를 반영한 교육용 단순화 NOI입니다.'},
      {name:'FINANCE',title:'빌릴 수 있는 돈과 감당할 수 있는 돈은 같지 않습니다.',body:'대출을 많이 받을수록 내 돈은 덜 들어가지만 금융비용과 금리 민감도는 커질 수 있습니다. 두 구조를 동시에 봅니다.',support:'A 대출 6억·5%·연이자 3,000만 / B 대출 10억·7%·연이자 7,000만',decision:'금융비용은 A가 유리하고, 초기 유동성은 B가 유리합니다.',note:'이 사례에서는 A를 일반 승인범위, B를 추가 한도 승인 조건으로 가정합니다.'},
      {name:'TENANCY',title:'현재 월세보다, 그 월세가 얼마나 유지될 수 있는지를 봅니다.',body:'임대수입이 누구에게 집중돼 있는지, 계약이 언제 끝나는지, 공실이 생기면 다시 채울 수 있는지를 따로 봅니다.',support:'임차인 4곳 + 공실 1곳 / 핵심 임차인 연 3,600만 / 현재수입의 약 43% / 잔여 14개월',decision:'한 임차인의 계약변화가 전체 수입에 미치는 영향이 큽니다.',note:'43% 자체를 위험 기준으로 보지 않습니다. 재계약 가능성·시장임대료·공간의 재임대성을 함께 확인합니다.'},
      {name:'BUILDING',title:'건물의 단점은 결국 비용과 활용성으로 연결됩니다.',body:'연식만 보는 대신 어떤 수선이 언제 필요하고, 그 비용이 임대와 가격에 어떤 영향을 주는지 봅니다.',support:'준공 24년 / 옥상 2,000만 / 외벽 1,500만 / 냉난방 1,500만 / 단기 수선 약 5,000만',decision:'단기 현금소요는 불리하지만, 가격에 충분히 반영됐다면 일부 상쇄될 수 있습니다.',note:'건물 자체의 문제는 발견하는 데서 끝나지 않고 총투자비와 재임대 경쟁력까지 연결해 봅니다.'},
      {name:'SURVIVAL',title:'조건이 틀렸을 때 어디까지 버틸 수 있을까요?',body:'미래를 맞히는 대신 금리·공실·수선 조건을 바꿔 현금흐름이 어떻게 달라지는지 확인합니다.',support:'CURRENT: A +4,000 / B 0 · CONSERVATIVE: A +2,500 / B -1,900 · STRONG: A +1,000 / B -3,800',decision:'선택한 시나리오에 따라 현금흐름 대응력의 차이가 명확해집니다.',note:'CURRENT / CONSERVATIVE / STRONG STRESS 중 하나를 선택합니다. 수선비는 반복 현금흐름과 분리해 일회성 필요자금으로 표시합니다.'},
      {name:'SYNTHESIS',title:'하나의 숫자로 결론내리지 않습니다.',body:'가격·수익·금융·임대·건물·생존성을 한 화면에서 다시 연결합니다. 각 축의 강점과 약점을 따로 보고, 어떤 조건이 바뀌면 결과도 달라지는지 확인합니다.',support:'PRICE / INCOME / FINANCE / TENANCY / BUILDING / SURVIVAL',decision:'근거가 있는 축에서는 유리·불리를 분명히 말하되 하나의 축으로 전체 매수 결론을 대신하지 않습니다.',note:'가장 강한 조건 / 가장 약한 조건 / 결과를 바꾸는 조건을 마지막에 남깁니다.'},
      {name:'FINAL FRAME',title:'처음에는 가격과 수익률을 봤습니다.',body:'이제는 그 숫자가 왜 만들어졌고, 어떤 조건에서 달라지는지를 봅니다.',support:'처음: 15억 · 6.4% / 지금: PRICE · NOI · FINANCE · TENANCY · BUILDING · SURVIVAL',decision:'건물을 어떻게 분석해야 하는지 보는 기준이 생겼습니다.',note:'좋은 건물인지 묻기보다, 어떤 조건에서 좋은 건물인지 분석합니다.'},
    ],bands:[['PRICE','비교범위 상단','다소 불리'],['INCOME','6.4% → 약 4.7%','표면 대비 수익매력 감소'],['FINANCE','A 3,000 / B 7,000','A 금융비용 우위'],['TENANCY','핵심 임차인 43%','계약변화 영향도 큼'],['BUILDING','단기 수선 5,000만','초기 현금소요 부담']]},
    final:{eyebrow:'ANALYSIS COMPLETE',title:'처음에는 가격과 수익률을 봤습니다.',lead:'이제는 그 숫자가 왜 만들어졌고, 어떤 조건에서 달라지는지를 봅니다.',outcome:'건물을 어떻게 분석해야 하는지 보는 기준이 생겼습니다.',closing:'좋은 건물인지 묻기보다, 어떤 조건에서 좋은 건물인지 분석합니다.',before:'처음',now:'지금',note:'이 페이지는 투자·감정평가·법률 자문을 대신하지 않습니다.',axes:finalMap},
  },
  en:{
    metaTitle:'How to Analyze a Building | FIX BUILDING',metaDescription:'Learn how to read a building through six practical axes: price, income, rights, building condition, location and operation, with seven supporting tools.',
    hero:{eyebrow:'02 · ANALYSIS',title:'What should you analyze,\nand in what order?',lead:'Do not start by asking whether a building is “good.” Start by explaining its price, what remains after costs, and which conditions can change the outcome.',cta:'Explore the six axes',note:'PRICE → INCOME → FINANCE → TENANCY → BUILDING → SURVIVAL'},
    map:{eyebrow:'ANALYSIS MAP',title:'See one building from six directions.',lead:'No single axis replaces the whole decision. Build evidence axis by axis, then connect the conditions.',items:[['PRICE','Why is this price this price?','Explain differences between comparable transactions.'],['INCOME','What actually remains after rent?', 'Move from full occupancy to operating income.'],['FINANCE','Borrowable and bearable are not the same.','Compare financing cost with retained liquidity.'],['TENANCY','Can today’s rent persist?','Check concentration, expiry and reletting.'],['BUILDING','What does the building itself demand?','Translate condition into cost, usability and price.'],['SURVIVAL','Can you keep holding if conditions worsen?','Stress recurring cash flow and liquidity.']]},
    axis:{
      price:{num:'01',question:'Why is this price this price?',intro:'Do not anchor on the asking price. Start with the conditions that explain why similar deals traded differently.',flow:'Ask → comparables → unit price → condition gaps → premium evidence → income cross-check',rule:'Explain the price before evaluating it.',verdict:'Without an additional advantage, the price position is somewhat unfavorable.',note:'Build the comparison frame first so the first asking price does not become the anchor for every judgment that follows.',button:'COMPARE CONDITIONS',target:'Target 1.50B KRW'},
      income:{num:'02',question:'What actually remains after rent?',intro:'Subtract vacancy and owner-paid operating costs from full-occupancy rent to reveal the operating structure.',flow:'Full rent → vacancy loss → current rent → operating cost → simplified NOI',rule:'Focus on what remains after vacancy and costs.',verdict:'Income appeal is lower after vacancy and operating costs than the headline yield suggests.',note:'Distinguish between a yield that is truly high after costs and one that only looks high because risk and costs are embedded in it.',labels:['Full occupancy','After vacancy','Simplified NOI'],deduct:['Vacancy -12M','Opex -14M']},
      finance:{num:'03',question:'Borrowable and bearable are not the same.',intro:'A larger loan can reduce equity while hiding higher financing cost and rate sensitivity.',flow:'Loan → rate → annual interest → equity → retained liquidity → rate sensitivity',rule:'Do not look at the loan limit alone; compare financing cost with the liquidity that remains.',verdict:'A is better on financing cost; B is better on initial liquidity.',verdictA:'A has the financing-cost advantage.',verdictB:'B has the initial-liquidity advantage.',note:'Actual loan terms vary by borrower, collateral and approval structure.',labels:{loan:'LOAN',equity:'EQUITY',interest:'ANNUAL INTEREST'}},
      tenancy:{num:'04',question:'Can today’s rental income persist?',intro:'High rent can change quickly when income is concentrated in one tenant or lease expiries are clustered.',flow:'Current rent → concentration → expiry → vacancy → reletting → market rent',rule:'Look beyond today’s rent to how long it can persist.',verdict:'A change in one tenant can have a large impact on total income.',note:'Evaluate the quality of the current lease separately from the competitiveness of the space after a tenant leaves.',key:'KEY TENANT',vacant:'VACANT',timeline:'14 months remaining'},
      building:{num:'05',question:'What building issues do the numbers miss?',intro:'Age alone matters less than which costs arrive, when they arrive, and how they constrain use or leasing.',flow:'Condition → repair → timing → usability → structural constraints → price impact',rule:'Translate building weaknesses into cost, leasing and price.',verdict:'Near-term cash demand is unfavorable, but it may be partly offset if the price already reflects it.',note:'Rights, lawful use and contract conditions require separate verification.',pins:{roof:'ROOF',exterior:'EXTERIOR',hvac:'HVAC'},repair:'NEAR-TERM REPAIR'},
      survival:{num:'06',question:'Can you keep holding if conditions worsen?',intro:'Instead of forecasting the future, test how recurring cash flow and liquidity react when assumptions are wrong.',flow:'Current → rate shock → vacancy shock → repair cash → recurring cash flow → liquidity',rule:'Do not predict; calculate how far the structure can bend.',verdict:'The selected scenario makes the difference in A/B cash-flow resilience visible.',note:'Stress values are sensitivity scenarios for learning, not forecasts.',educationNote:'Scenario rates, vacancy periods and repair costs are educational assumptions for explaining the method, not market benchmarks.',scenarioLeads:{current:'If current conditions hold',conservative:'If conditions move somewhat against you',stress:'If several conditions worsen at once'},repeated:'ANNUAL RECURRING CASH FLOW · KRW 10K',rate:'RATE',vacancy:'VACANCY',cashNeed:'ONE-TIME CASH NEED',months:' months',none:'None added'},
    },
    case:{eyebrow:'FULL ANALYSIS CASE',title:'A KRW 1.5B building. What should you look at first?',lead:'At first, visible numbers such as price and rental income draw attention. But those numbers alone are not enough to decide.',prev:'PREV',next:'NEXT',start:'START ANALYSIS',finish:'FINAL FRAME',scenario:'SCENARIO',steps:[
      {name:'CASE START',title:'A KRW 1.5B building. What should you look at first?',body:'At first, visible numbers such as price and rental income draw attention. But those numbers alone are not enough to decide.',support:'Asking KRW 1.5B · full-occupancy annual rent KRW 96M · headline yield 6.4% · 24 years old · 1 vacancy',decision:'No verdict yet.',note:'Break this building down in order from PRICE through SURVIVAL.'},
      {name:'BASELINE',title:'Set the baseline before looking at the building.',body:'If you change your standards to fit an attractive property, the decision becomes unstable. Set affordable capital and the cash reserve first.',support:'Available cash KRW 1.1B · minimum reserve KRW 100M · long-term hold',decision:'The baseline is set first.',note:'Do not ask only how much can go into the purchase price; also ask what remains after purchase.'},
      {name:'PRICE',title:'Explain the price before evaluating it.',body:'Instead of relying on whether the asking price feels cheap or expensive, first explain why similar transactions closed at different prices.',support:'Target KRW 1.50B · A 1.42B · B 1.51B · C 1.38B',decision:'Without an additional advantage, the price position is somewhat unfavorable.',note:'If comparable pricing and the current income structure imply very different values, investigate the reason for the gap.'},
      {name:'INCOME',title:'Look at what actually remains, not just rent.',body:'Subtract vacancy and owner-paid operating expenses from full occupancy to reveal the operating-income structure.',support:'KRW 96M → 84M → 70M · 6.4% → about 4.7%',decision:'Income appeal is lower after vacancy and operating costs than the headline yield suggests.',note:'KRW 70M is a simplified educational NOI after vacancy and owner-paid operating expenses in this case.'},
      {name:'FINANCE',title:'Borrowable and bearable are not the same.',body:'More debt can reduce the cash you put in, but financing cost and rate sensitivity can increase. Compare both structures at the same time.',support:'A: KRW 600M loan · 5% · KRW 30M annual interest · B: KRW 1.0B · 7% · KRW 70M',decision:'A has the financing-cost advantage, while B has the initial-liquidity advantage.',note:'For this educational case, A is the ordinary approval range and B assumes an additional-limit approval.'},
      {name:'TENANCY',title:'Look beyond today’s rent to how long it can persist.',body:'Separate who generates the rent, when leases expire, and whether vacant space can be leased again.',support:'4 tenants + 1 vacancy · key tenant KRW 36M/year · about 43% of current rent · 14 months remaining',decision:'A change in one tenant can have a large impact on total income.',note:'43% is not an absolute risk threshold. Review renewal prospects, market rent and reletting ability together.'},
      {name:'BUILDING',title:'Building weaknesses eventually become cost and usability issues.',body:'Instead of judging age alone, check which repairs are needed, when the cash is required, and how those items affect leasing and price.',support:'24 years · roof KRW 20M · exterior KRW 15M · HVAC KRW 15M · near-term repair about KRW 50M',decision:'Near-term cash demand is unfavorable, but it may be partly offset if the price already reflects it.',note:'Connect building issues to total investment cost and reletting competitiveness rather than stopping at defect discovery.'},
      {name:'SURVIVAL',title:'How far can the structure hold when assumptions are wrong?',body:'Instead of predicting the future, change rate, vacancy and repair assumptions and observe how cash flow changes.',support:'CURRENT · CONSERVATIVE · STRONG STRESS',decision:'The selected scenario makes the difference in cash-flow resilience visible.',note:'Keep repairs separate from recurring cash flow and show them as a one-time cash need.'},
      {name:'SYNTHESIS',title:'Do not collapse the case into one number.',body:'Reconnect price, income, finance, tenancy, building and survival on one screen. Keep strengths and weaknesses separate and identify which changing conditions alter the result.',support:'PRICE · INCOME · FINANCE · TENANCY · BUILDING · SURVIVAL',decision:'Where evidence supports it, state favorable or unfavorable clearly, but do not let one axis replace the whole purchase decision.',note:'Leave the strongest condition, weakest condition and conditions that change the result visible at the end.'},
      {name:'FINAL FRAME',title:'At first, we saw price and yield.',body:'Now we see why those numbers were created and under which conditions they change.',support:'Before: KRW 1.5B · 6.4% → Now: PRICE · NOI · FINANCE · TENANCY · BUILDING · SURVIVAL',decision:'You now have a framework for how to analyze a building.',note:'Instead of asking whether it is a good building, analyze the conditions under which it is good.'},
    ],bands:[['PRICE','Upper end of comps','Somewhat unfavorable'],['INCOME','6.4% → ~4.7%','Headline appeal falls'],['FINANCE','A 30M / B 70M','A financing-cost advantage'],['TENANCY','Key tenant 43%','High change impact'],['BUILDING','Near-term 50M','Initial cash burden']]},
    final:{eyebrow:'ANALYSIS COMPLETE',title:'At first, we saw price and yield.',lead:'Now we see why those numbers were created and under which conditions they change.',outcome:'You now have a framework for how to analyze a building.',closing:'Instead of asking whether it is a good building, analyze the conditions under which it is good.',before:'BEFORE',now:'NOW',note:'This page does not replace investment, appraisal or legal advice.',axes:finalMap},
  },
  ja:{
    metaTitle:'建物の分析方法 | FIX BUILDING',metaDescription:'価格・収益・権利・建物・立地・運営の6つの基準と7つの分析ツールで、建物を見る順序を分かりやすく学ぶガイド。',
    hero:{eyebrow:'02 · ANALYSIS',title:'建物は何を、\nどの順番で分析するのか。',lead:'最初から「良い建物か」を決めません。価格がなぜ形成され、実際に何が残り、どの条件で結果が変わるのかを順番に確認します。',cta:'6つの分析軸を見る',note:'PRICE → INCOME → FINANCE → TENANCY → BUILDING → SURVIVAL'},
    map:{eyebrow:'ANALYSIS MAP',title:'一つの建物を6方向から見ます。',lead:'一つの数値や軸で全体結論を代用しません。各軸の根拠を確認して最後に条件をつなぎます。',items:[['PRICE','この価格はなぜこの価格なのか？','類似取引の価格差を作った条件を確認。'],['INCOME','家賃ではなく実際にいくら残るか？','空室と運営費を引いた収益を見る。'],['FINANCE','借りられる額と負担できる額は同じか？','金融費用と残る流動性を比較。'],['TENANCY','今の賃料収入は維持できるか？','集中度と契約変更の影響を見る。'],['BUILDING','数字に出ない建物の問題はないか？','状態を修繕費・活用性・価格影響に変換。'],['SURVIVAL','状況が悪化しても保有を続けられるか？','条件悪化時のキャッシュフローを確認。']]},
    axis:{
      price:{num:'01',question:'この価格はなぜこの価格なのか？',intro:'売出価格を基準点にしません。類似取引の価格差を作った条件から確認します。',flow:'売出価格 → 比較価格 → 単価 → 条件差 → プレミアム根拠 → 収益構造との交差確認',rule:'価格を評価する前に、価格を説明します。',verdict:'追加の優位性が確認できなければ、価格面ではやや不利です。',note:'最初に見た売出価格がその後の判断の基準点にならないよう、先に比較基準を作ります。',button:'条件を比較',target:'対象 15.0億ウォン'},
      income:{num:'02',question:'家賃ではなく実際にいくら残るか？',intro:'満室賃料から空室損失と所有者負担運営費を順に引くと運営収益構造が見えます。',flow:'満室収入 → 空室損失 → 現在収入 → 運営費 → 簡易NOI',rule:'高い家賃より、空室と費用の後に残る構造を見ます。',verdict:'空室・運営費を反映すると表面利回りより収益魅力は下がります。',note:'高い利回りが実際に残るから高いのか、リスクと費用で高く見えるのかを分けて考えます。',labels:['満室基準','空室反映','簡易NOI（純営業収益）'],deduct:['空室損失 -1,200万','運営費 -1,400万']},
      finance:{num:'03',question:'借りられる額と負担できる額は同じか？',intro:'融資枠だけを見ると自己資金は減りますが、金融費用と金利感応度が隠れます。',flow:'融資額 → 金利 → 年間金融費用 → 自己資金 → 流動性 → 金利感応度',rule:'融資枠だけでなく、金融費用と残る流動性を一緒に見ます。',verdict:'金融費用はAが有利、初期流動性はBが有利です。',verdictA:'金融費用はAが有利です。',verdictB:'初期流動性はBが有利です。',note:'実際の融資条件は借り手・担保・承認構造によって異なります。',labels:{loan:'融資',equity:'自己資金',interest:'年間利息'}},
      tenancy:{num:'04',question:'今の賃料収入は維持できるか？',intro:'一つのテナントへの集中や契約満了の偏りがあると収益構造は簡単に変わります。',flow:'現在収入 → 集中度 → 契約満了 → 空室 → 再賃貸 → 市場賃料',rule:'現在の家賃より、その家賃がどれだけ維持できるかを見ます。',verdict:'一つのテナントの契約変化が全体収入に与える影響が大きいです。',note:'現在の契約の質と、退去後の空間競争力を分けて見ます。',key:'主要テナント',vacant:'空室',timeline:'残存14か月'},
      building:{num:'05',question:'数字に出ない建物自体の問題はないか？',intro:'築年数そのものより、どの費用がいつ発生し、活用や賃貸にどの制約を作るかが重要です。',flow:'状態 → 修繕 → 時期 → 活用性 → 構造制約 → 価格反映',rule:'弱点を費用・賃貸・価格への影響に変換します。',verdict:'短期の現金需要は不利ですが、価格に十分反映されていれば一部相殺できます。',note:'権利・法的使用可能性・契約条件は別途確認が必要です。',pins:{roof:'ROOF',exterior:'EXTERIOR',hvac:'HVAC'},repair:'NEAR-TERM REPAIR'},
      survival:{num:'06',question:'状況が悪化しても保有を続けられるか？',intro:'未来予測ではなく、前提が外れた時に反復キャッシュフローと流動性がどれだけ動くかを確認します。',flow:'現在 → 金利ショック → 空室ショック → 修繕費 → 反復CF → 流動性',rule:'未来を当てず、条件が外れた時にどこまで耐えられるかを計算します。',verdict:'選択したシナリオでA/Bのキャッシュフロー耐性差が明確になります。',note:'ストレス値は予測ではなく、教育用の感応度シナリオです。',educationNote:'シナリオの金利・空室期間・修繕費は分析方法を説明するための教育用仮定であり、市場の基準値ではありません。',scenarioLeads:{current:'現在条件が続く場合',conservative:'条件が少し不利に動く場合',stress:'複数条件が同時に大きく悪化する場合'},repeated:'年間反復キャッシュフロー · 単位 万ウォン',rate:'RATE',vacancy:'VACANCY',cashNeed:'ONE-TIME CASH NEED',months:'か月',none:'追加なし'},
    },
    case:{eyebrow:'FULL ANALYSIS CASE',title:'15億ウォンの建物。何から見るべきでしょうか？',lead:'最初は価格や賃料収入のような見えやすい数字に目が向きます。しかし、この情報だけではまだ判断しません。',prev:'PREV',next:'NEXT',start:'分析開始',finish:'最終フレーム',scenario:'選択シナリオ',steps:[
      {name:'CASE START',title:'15億ウォンの建物。何から見るべきでしょうか？',body:'最初は価格や賃料収入のような見えやすい数字に目が向きます。しかし、この情報だけではまだ判断しません。',support:'売出15億 · 満室基準の年間賃料9,600万 · 単純表面利回り6.4% · 築24年 · 空室1',decision:'まだ判定しません。',note:'この建物をPRICEからSURVIVALまで順番に分解します。'},
      {name:'BASELINE',title:'建物を見る前に基準を先に決めます。',body:'良く見える物件に合わせて基準を変えると判断が揺れます。負担できる資金と残す現金を先に決めます。',support:'利用可能現金11億 · 最低保有現金1億 · 長期保有前提',decision:'基準を先に設定した状態です。',note:'購入代金にいくら入れられるかだけでなく、購入後に何が残るかも一緒に見ます。'},
      {name:'PRICE',title:'価格を評価する前に、価格を説明します。',body:'売出価格が安いか高いかという感覚より、似た取引がなぜ異なる価格で成立したのかを先に見ます。',support:'対象15.0億 · A14.2億 · B15.1億 · C13.8億',decision:'追加の優位性が確認できなければ、価格面ではやや不利です。',note:'比較価格と現在の収益構造で説明される価格が大きく異なるなら、その差の理由を再確認します。'},
      {name:'INCOME',title:'家賃ではなく実際にいくら残るかを見ます。',body:'満室数字から空室と所有者負担の運営費を順に引くと、建物の運営収益構造が見えます。',support:'9,600万 → 8,400万 → 7,000万 · 6.4% → 約4.7%',decision:'空室・運営費を反映すると、表面利回りより収益魅力は低下します。',note:'7,000万は、このケースで空室と所有者負担運営費を反映した教育用の簡易NOIです。'},
      {name:'FINANCE',title:'借りられる額と負担できる額は同じではありません。',body:'融資を増やすと自己資金は減りますが、金融費用と金利感応度は高まる可能性があります。二つの構造を同時に見ます。',support:'A 融資6億·5%·年利息3,000万 · B 融資10億·7%·年利息7,000万',decision:'金融費用はAが有利で、初期流動性はBが有利です。',note:'このケースではAを一般承認範囲、Bを追加枠承認条件と仮定します。'},
      {name:'TENANCY',title:'現在の家賃より、その家賃がどれだけ維持できるかを見ます。',body:'賃料収入が誰に集中しているか、契約がいつ終わるか、空室が生じた時に再び埋められるかを分けて見ます。',support:'テナント4 + 空室1 · 主要テナント年3,600万 · 現在収入の約43% · 残存14か月',decision:'一つのテナントの契約変化が全体収入に与える影響が大きいです。',note:'43%自体を危険基準にはしません。更新可能性・市場賃料・空間の再賃貸性を一緒に確認します。'},
      {name:'BUILDING',title:'建物の弱点は最終的に費用と活用性につながります。',body:'築年数だけを見るのではなく、どの修繕がいつ必要で、その費用が賃貸と価格にどう影響するかを見ます。',support:'築24年 · 屋上2,000万 · 外壁1,500万 · HVAC1,500万 · 短期修繕約5,000万',decision:'短期の現金需要は不利ですが、価格に十分反映されていれば一部相殺できます。',note:'建物自体の問題は発見で終わらせず、総投資額と再賃貸競争力までつなげて見ます。'},
      {name:'SURVIVAL',title:'条件が外れた時、どこまで耐えられるでしょうか？',body:'未来を当てるのではなく、金利・空室・修繕条件を変えてキャッシュフローがどう変化するかを確認します。',support:'CURRENT · CONSERVATIVE · STRONG STRESS',decision:'選択したシナリオによってキャッシュフロー対応力の差が明確になります。',note:'修繕費は反復キャッシュフローと分離し、一時的必要資金として表示します。'},
      {name:'SYNTHESIS',title:'一つの数字で結論を出しません。',body:'価格・収益・金融・賃貸・建物・生存性を一画面で再びつなぎます。各軸の強みと弱みを分け、どの条件が変わると結果も変わるか確認します。',support:'PRICE · INCOME · FINANCE · TENANCY · BUILDING · SURVIVAL',decision:'根拠がある軸では有利・不利を明確にしつつ、一つの軸で全体の購入結論を代用しません。',note:'最も強い条件 · 最も弱い条件 · 結果を変える条件を最後に残します。'},
      {name:'FINAL FRAME',title:'最初は価格と利回りを見ました。',body:'今は、その数字がなぜ作られ、どの条件で変わるかを見ます。',support:'最初: 15億 · 6.4% → 今: PRICE · NOI · FINANCE · TENANCY · BUILDING · SURVIVAL',decision:'建物をどのように分析すべきかを見る基準ができました。',note:'良い建物かと問うより、どの条件で良い建物なのかを分析します。'},
    ],bands:[['PRICE','比較範囲上端','やや不利'],['INCOME','6.4% → 約4.7%','収益魅力低下'],['FINANCE','A 3,000 / B 7,000','A金融費用優位'],['TENANCY','主要43%','契約変化影響大'],['BUILDING','短期5,000万','初期現金負担']]},
    final:{eyebrow:'ANALYSIS COMPLETE',title:'最初は価格と利回りを見ました。',lead:'今は、その数字がなぜ作られ、どの条件で変わるかを見ます。',outcome:'建物をどのように分析するか、その基準ができました。',closing:'良い建物かと問うより、どの条件で良い建物なのかを分析します。',before:'最初',now:'今',note:'このページは投資・鑑定評価・法律助言を代替しません。',axes:finalMap},
  },
};

export const ANALYSIS_UI_COPY = {
  ko:{
    startHere:'START HERE',nextAxis:'NEXT',progress:'분석 순서',rule:'RULE',yieldShift:'YIELD SHIFT',fullCase:'FULL CASE',scenarioAria:'시나리오 선택',cashFlowAria:'A/B 반복 현금흐름 비교',evidence:'근거 숫자',judgment:'판정',caseNote:'교육용 사례이며 실제 특정 매물을 의미하지 않습니다.',
    learning:{eyebrow:'LEARN THE SIX AXES',part1:'PART 1 · 6가지 분석법 학습',part2:'PART 2 · 실전 적용 학습',title:'6가지 분석법을 순서대로 배웁니다.',lead:'PRICE부터 SURVIVAL까지 한 가지씩 학습합니다. 여섯 분석법을 모두 익힌 뒤 같은 기준을 한 건물에 실제로 적용합니다.',route:'PRICE → INCOME → FINANCE → TENANCY → BUILDING → SURVIVAL 순서로 진행합니다.',start:'6가지 분석법 학습 시작',courseIntro:'먼저 분석 기준부터 배웁니다.',courseIntroLead:'지금은 매물을 판단하지 않습니다. 각 축에서 무엇을 보고, 어떤 순서로 근거를 만들고, 어디까지 판정할 수 있는지를 익힙니다.',prev:'이전',next:'다음 분석법',complete:'6가지 분석법 학습 완료',progressAria:'6축 학습 진행상태',bridgeEyebrow:'PART 1 COMPLETE',bridgeTitle:'이제 6가지 분석법을 한 건물에 적용합니다.',bridgeLead:'앞에서 배운 PRICE · INCOME · FINANCE · TENANCY · BUILDING · SURVIVAL을 15억 사례에 같은 순서로 적용합니다.',bridgeCta:'실전 적용 학습 시작',caseStarted:'6축 학습 완료 · 실전 적용 중',lockedTitle:'먼저 6가지 분석법을 순서대로 확인합니다.',lockedLead:'FULL ANALYSIS CASE는 6축 학습을 마치면 이어서 열립니다.',backToLearning:'6축 학습으로 돌아가기'},
    caseCtas:['분석 시작','가격 분석','수익 분석','금융 분석','임대 분석','건물 분석','생존성 분석','종합 분석 보기','마지막 프레임','ANALYSIS 종료'],
    caseEyebrows:['FULL ANALYSIS CASE','STEP 1 · BASELINE','STEP 2 · PRICE','STEP 3 · INCOME','STEP 4 · FINANCE','STEP 5 · TENANCY','STEP 6 · BUILDING','STEP 7 · SURVIVAL','STEP 8 · SYNTHESIS','ANALYSIS COMPLETE'],
    caseSecondaryLabels:['지방 주요상권 · 중소형 상가건물','매입대금 외 취득·초기비용은 별도','A 규모 유사·연식 열위·일부 공실 / B 규모 유사·연식 우위·만실 / C 입지 한 단계 열위·상태 유사','공실손실 -1,200만 / 운영비 -1,400만 / 단순화한 NOI 약 7,000만','A 매입대금 자기자본 9억 / B 5억','핵심 임차인 영향도','NEAR-TERM REPAIR','연 반복 현금흐름 · 단위 만원','선택 시나리오 결과 반영','가장 강한 조건 / 가장 약한 조건 / 결과를 바꾸는 조건'],
    caseFooterNotes:['교육용 사례이며 실제 특정 매물을 의미하지 않습니다.','사례의 자금조건은 교육용 가정입니다.','비교거래의 단순 평균을 적정가로 사용하지 않습니다.','취득비용·세금·금융비용 등은 이 단계에 포함하지 않습니다.','대출액이 늘면 금리가 자동으로 오른다는 의미는 아닙니다.','임차인 수보다 임대수입 집중도와 계약만료 구조를 우선합니다.','권리·법적 사용가능성·계약조건은 별도 확인이 필요합니다.','시나리오의 금리·공실기간·수선비는 교육용 가정이며 시장의 기준값을 의미하지 않습니다.','점수·등급·종합 위험점수는 사용하지 않습니다.','이 페이지는 투자·감정평가·법률 자문을 대신하지 않습니다.'],
    assumptions:'시나리오 가정',rateImpact:'금리 영향',vacancyImpact:'공실 영향',oneTimeSeparate:'반복 현금흐름과 분리한 일회성 필요자금',scenarioFixedNote:'같은 건물도 금융구조와 가정한 조건에 따라 결과가 달라집니다.',
    scenarioResults:{
      current:{A:'금융비용 반영 후 반복 현금흐름이 플러스를 유지합니다.',B:'운영수익 대부분이 금융비용으로 소진됩니다.'},
      conservative:{A:'반복 현금흐름은 플러스를 유지합니다. 현금흐름 대응력은 B보다 유리합니다.',B:'반복 현금흐름이 적자로 전환됩니다. 다만 초기 유동성은 A보다 큽니다.'},
      stress:{A:'반복 현금흐름은 플러스를 유지하지만 여유 폭이 크게 줄어듭니다.',B:'반복 현금흐름 적자 폭이 커집니다. 초기 유동성이 손실 흡수의 핵심이 됩니다.'}
    },
    scenarioAssumptions:{current:'추가 금리상승 없음 / 추가 핵심임차인 공실 없음 / 추가 수선비 없음',conservative:'금리 +1%p / 핵심 임차인 3개월 공실 / 일회성 수선 2,000만',stress:'금리 +2%p / 핵심 임차인 6개월 공실 / 일회성 수선 5,000만'},
    baseline:{available:'총 가용현금',reserve:'최소 보유현금 목표',deployable:'매입대금 투입 가능',initialCost:'취득·초기비용',separate:'별도',initialCostNote:'매입대금 외 취득·초기비용은 별도',hold:'장기보유 전제'},
    caseLabels:{asking:'호가',fullRent:'만실 연 임대수입',yield:'단순 표면수익률',age:'준공',vacancy:'공실'},
    tenancy:{instruction:'핵심 임차인을 선택해 수입 집중도와 계약만료를 확인합니다.',select:'핵심 임차인 보기',reset:'전체 구조 보기',keyAria:'핵심 임차인 선택',tenant:'임차인',year:'연',incomeShare:'현재 실제 임대수입 비중',now:'현재',monthShort:'개월'},
    building:{age:'준공 후',yearShort:'년'},
    final:{surface:'PRICE + YIELD'},
    finalConditions:{current:{strong:'A는 금융비용 반영 후 반복 현금흐름 +4,000만원을 유지합니다.',weak:'B는 반복 현금흐름이 0으로 운영수익 대부분이 금융비용에 소진됩니다.',changes:'금리 · 핵심 임차인 공실 · 수선비'},conservative:{strong:'A는 보수 시나리오에서도 반복 현금흐름 +2,500만원을 유지합니다.',weak:'B는 반복 현금흐름 -1,900만원으로 전환됩니다.',changes:'금리 +1%p · 핵심 임차인 3개월 공실 · 일회성 수선 2,000만원'},stress:{strong:'A는 강한 스트레스에서도 +1,000만원을 유지하지만 여유 폭이 작습니다.',weak:'B는 반복 현금흐름 -3,800만원으로 적자 폭이 커집니다.',changes:'금리 +2%p · 핵심 임차인 6개월 공실 · 일회성 수선 5,000만원'}},
    strong:'강한 조건',weak:'약한 조건',changes:'결과를 바꾸는 조건',
    finalStrong:'A 금융구조의 낮은 금융비용',finalWeak:'B 금융구조의 스트레스 현금흐름',finalChanges:'금리 · 핵심 임차인 공실 · 수선비'
  },
  en:{
    startHere:'START HERE',nextAxis:'NEXT',progress:'ANALYSIS ORDER',rule:'RULE',yieldShift:'YIELD SHIFT',fullCase:'FULL CASE',scenarioAria:'Scenario selection',cashFlowAria:'A/B recurring cash flow comparison',evidence:'EVIDENCE',judgment:'JUDGMENT',caseNote:'Educational case; not a specific real property.',
    learning:{eyebrow:'LEARN THE SIX AXES',part1:'PART 1 · LEARN SIX ANALYSIS METHODS',part2:'PART 2 · APPLY THEM TO A CASE',title:'Learn the six axes in order.',lead:'Learn one method at a time from PRICE to SURVIVAL. After all six, apply the same framework to one building.',route:'PRICE → INCOME → FINANCE → TENANCY → BUILDING → SURVIVAL, in that order.',start:'START SIX-AXIS LEARNING',courseIntro:'Learn the analysis framework first.',courseIntroLead:'Do not judge the property yet. Learn what each axis checks, how evidence is built, and what can be concluded from it.',prev:'PREV',next:'NEXT METHOD',complete:'SIX METHODS LEARNED',progressAria:'Six-axis learning progress',bridgeEyebrow:'PART 1 COMPLETE',bridgeTitle:'Now apply the six methods to one building.',bridgeLead:'Use PRICE · INCOME · FINANCE · TENANCY · BUILDING · SURVIVAL on the KRW 1.5B case in the same order.',bridgeCta:'START PRACTICAL CASE',caseStarted:'SIX AXES COMPLETE · PRACTICAL CASE',lockedTitle:'Complete the six axes first.',lockedLead:'The FULL ANALYSIS CASE opens after the six-axis learning sequence is complete.',backToLearning:'BACK TO SIX AXES'},
    caseCtas:['START ANALYSIS','PRICE ANALYSIS','INCOME ANALYSIS','FINANCE ANALYSIS','TENANCY ANALYSIS','BUILDING ANALYSIS','SURVIVAL ANALYSIS','VIEW SYNTHESIS','FINAL FRAME','END ANALYSIS'],
    caseEyebrows:['FULL ANALYSIS CASE','STEP 1 · BASELINE','STEP 2 · PRICE','STEP 3 · INCOME','STEP 4 · FINANCE','STEP 5 · TENANCY','STEP 6 · BUILDING','STEP 7 · SURVIVAL','STEP 8 · SYNTHESIS','ANALYSIS COMPLETE'],
    caseSecondaryLabels:['Major regional commercial district · small-to-mid-size retail building','Acquisition and initial costs are separate from the purchase price','A similar scale·older·partial vacancy / B similar scale·newer·full / C weaker location·similar condition','Vacancy loss -KRW 12M / operating cost -KRW 14M / simplified NOI about KRW 70M','A purchase equity KRW 900M / B KRW 500M','Key-tenant impact','NEAR-TERM REPAIR','Recurring annual cash flow · KRW 10K units','Selected scenario reflected','Strongest condition / weakest condition / what changes the result'],
    caseFooterNotes:['Educational case; not a specific real property.','The funding conditions are educational assumptions.','Do not use a simple average of comparables as fair value.','Acquisition costs, taxes and financing costs are not included at this stage.','A larger loan does not automatically mean a higher rate.','Prioritize income concentration and lease expiry structure over tenant count.','Rights, legal usability and contract terms require separate verification.','Scenario rates, vacancy periods and repair costs are educational assumptions, not market benchmarks.','No score, grade or composite risk score is used.','This page does not replace investment, valuation or legal advice.'],
    assumptions:'SCENARIO ASSUMPTIONS',rateImpact:'RATE IMPACT',vacancyImpact:'VACANCY IMPACT',oneTimeSeparate:'One-time cash need, kept separate from recurring cash flow',scenarioFixedNote:'The same building produces different outcomes under different financing structures and assumed conditions.',
    scenarioResults:{current:{A:'Recurring cash flow stays positive after financing cost.',B:'Most operating income is consumed by financing cost.'},conservative:{A:'Recurring cash flow stays positive and is more resilient than B.',B:'Recurring cash flow turns negative, while initial liquidity remains higher than A.'},stress:{A:'Recurring cash flow stays positive but the margin narrows sharply.',B:'The recurring deficit widens; initial liquidity becomes the main loss buffer.'}},
    scenarioAssumptions:{current:'No added rate rise · no added key-tenant vacancy · no added repair',conservative:'Rate +1%p · key tenant vacant 3 months · one-time repair 20M',stress:'Rate +2%p · key tenant vacant 6 months · one-time repair 50M'},
    baseline:{available:'AVAILABLE CASH',reserve:'MINIMUM RESERVE',deployable:'DEPLOYABLE FOR PRICE',initialCost:'ACQUISITION / INITIAL COST',separate:'SEPARATE',initialCostNote:'Acquisition and initial costs are separate from the purchase price',hold:'LONG-TERM HOLD'},caseLabels:{asking:'ASKING',fullRent:'FULL RENT / YR',yield:'HEADLINE YIELD',age:'AGE',vacancy:'VACANCY'},
    tenancy:{instruction:'Select the key tenant to see income concentration and lease timing.',select:'VIEW KEY TENANT',reset:'VIEW ALL SPACES',keyAria:'Select key tenant',tenant:'TENANT',year:'YR',incomeShare:'SHARE OF CURRENT RENT',now:'NOW',monthShort:'M'},building:{age:'BUILDING AGE',yearShort:'Y'},final:{surface:'PRICE + YIELD'},finalConditions:{current:{strong:'A keeps positive recurring cash flow at KRW 40M after financing cost.',weak:'B is at zero recurring cash flow, with most operating income consumed by financing cost.',changes:'Rates · key-tenant vacancy · repairs'},conservative:{strong:'A keeps KRW 25M of recurring cash flow under the conservative scenario.',weak:'B turns to a KRW 19M recurring deficit.',changes:'Rate +1%p · key tenant vacant 3 months · one-time repair KRW 20M'},stress:{strong:'A remains positive at KRW 10M, but the margin is thin.',weak:'B widens to a KRW 38M recurring deficit.',changes:'Rate +2%p · key tenant vacant 6 months · one-time repair KRW 50M'}},
    strong:'STRONG CONDITION',weak:'WEAK CONDITION',changes:'WHAT CHANGES THE RESULT',finalStrong:'Lower financing cost in structure A',finalWeak:'Stress cash flow in structure B',finalChanges:'Rates · key-tenant vacancy · repairs'
  },
  ja:{
    startHere:'START HERE',nextAxis:'NEXT',progress:'分析順序',rule:'RULE',yieldShift:'YIELD SHIFT',fullCase:'FULL CASE',scenarioAria:'シナリオ選択',cashFlowAria:'A/B反復キャッシュフロー比較',evidence:'根拠数値',judgment:'判定',caseNote:'教育用ケースであり、実在する特定物件ではありません。',
    learning:{eyebrow:'LEARN THE SIX AXES',part1:'PART 1 · 6つの分析法を学ぶ',part2:'PART 2 · 実例に適用する',title:'6つの分析軸を順番に学びます。',lead:'PRICEからSURVIVALまで一つずつ学びます。6つを終えた後、同じ基準を一つの建物に適用します。',route:'PRICE → INCOME → FINANCE → TENANCY → BUILDING → SURVIVAL の順で進みます。',start:'6つの分析法を学ぶ',courseIntro:'まず分析の基準を学びます。',courseIntroLead:'まだ物件を判断しません。各軸で何を見るか、どの順序で根拠を作るか、どこまで判定できるかを学びます。',prev:'前へ',next:'次の分析法',complete:'6つの分析法を学習完了',progressAria:'6軸学習の進行状況',bridgeEyebrow:'PART 1 COMPLETE',bridgeTitle:'次に6つの分析法を一つの建物に適用します。',bridgeLead:'PRICE · INCOME · FINANCE · TENANCY · BUILDING · SURVIVALを15億ウォンのケースに同じ順序で適用します。',bridgeCta:'実践ケースを開始',caseStarted:'6軸学習完了 · 実践適用中',lockedTitle:'まず6つの分析軸を順番に確認します。',lockedLead:'FULL ANALYSIS CASEは6軸学習を完了すると開きます。',backToLearning:'6軸学習へ戻る'},
    caseCtas:['分析開始','価格分析','収益分析','金融分析','賃貸分析','建物分析','生存性分析','総合分析を見る','最終フレーム','ANALYSIS終了'],
    caseEyebrows:['FULL ANALYSIS CASE','STEP 1 · BASELINE','STEP 2 · PRICE','STEP 3 · INCOME','STEP 4 · FINANCE','STEP 5 · TENANCY','STEP 6 · BUILDING','STEP 7 · SURVIVAL','STEP 8 · SYNTHESIS','ANALYSIS COMPLETE'],
    caseSecondaryLabels:['地方主要商圏 · 中小型商業ビル','購入代金以外の取得・初期費用は別途','A 規模類似・築年数で劣位・一部空室 / B 規模類似・築年数で優位・満室 / C 立地一段劣位・状態類似','空室損失 -1,200万 / 運営費 -1,400万 / 簡易NOI 約7,000万','A 購入代金自己資金9億 / B 5億','主要テナント影響度','NEAR-TERM REPAIR','年間反復キャッシュフロー · 単位 万ウォン','選択シナリオ結果を反映','最も強い条件 / 最も弱い条件 / 結果を変える条件'],
    caseFooterNotes:['教育用ケースであり、実在する特定物件ではありません。','ケースの資金条件は教育用の仮定です。','比較取引の単純平均を適正価格として使用しません。','取得費用・税金・金融費用などはこの段階に含めません。','融資額が増えると金利が自動的に上がるという意味ではありません。','テナント数より賃料収入の集中度と契約満了構造を優先します。','権利・法的使用可能性・契約条件は別途確認が必要です。','シナリオの金利・空室期間・修繕費は教育用仮定であり、市場基準値ではありません。','点数・等級・総合リスク点数は使用しません。','このページは投資・鑑定評価・法律助言を代替しません。'],
    assumptions:'シナリオ仮定',rateImpact:'金利影響',vacancyImpact:'空室影響',oneTimeSeparate:'反復キャッシュフローと分離した一時的必要資金',scenarioFixedNote:'同じ建物でも、金融構造と仮定条件によって結果は変わります。',
    scenarioResults:{current:{A:'金融費用反映後も反復キャッシュフローはプラスを維持します。',B:'運営収益の大部分が金融費用で消費されます。'},conservative:{A:'反復キャッシュフローはプラスを維持し、Bより対応力があります。',B:'反復キャッシュフローは赤字に転換しますが、初期流動性はAより大きいです。'},stress:{A:'プラスを維持しますが余裕幅は大きく縮小します。',B:'反復赤字が拡大し、初期流動性が損失吸収の鍵になります。'}},
    scenarioAssumptions:{current:'追加金利上昇なし · 主要テナント追加空室なし · 追加修繕なし',conservative:'金利 +1%p · 主要テナント3か月空室 · 一時修繕2,000万',stress:'金利 +2%p · 主要テナント6か月空室 · 一時修繕5,000万'},
    baseline:{available:'利用可能現金',reserve:'最低保有現金',deployable:'購入代金に投入可能',initialCost:'取得・初期費用',separate:'別途',initialCostNote:'購入代金以外の取得・初期費用は別途',hold:'長期保有前提'},caseLabels:{asking:'売出価格',fullRent:'満室年賃料',yield:'表面利回り',age:'築年',vacancy:'空室'},
    tenancy:{instruction:'主要テナントを選び、収入集中度と契約満了を確認します。',select:'主要テナントを見る',reset:'全体構造を見る',keyAria:'主要テナントを選択',tenant:'テナント',year:'年',incomeShare:'現在賃料収入の比率',now:'現在',monthShort:'か月'},building:{age:'築',yearShort:'年'},final:{surface:'PRICE + YIELD'},finalConditions:{current:{strong:'Aは金融費用反映後も反復CF +4,000万ウォンを維持します。',weak:'Bは反復CFが0で、運営収益の大半が金融費用に消費されます。',changes:'金利 · 主要テナント空室 · 修繕費'},conservative:{strong:'Aは保守シナリオでも反復CF +2,500万ウォンを維持します。',weak:'Bは反復CF -1,900万ウォンに転換します。',changes:'金利 +1%p · 主要テナント3か月空室 · 一時修繕2,000万ウォン'},stress:{strong:'Aは強いストレスでも +1,000万ウォンを維持しますが余裕は小さいです。',weak:'Bは反復CF -3,800万ウォンまで赤字が拡大します。',changes:'金利 +2%p · 主要テナント6か月空室 · 一時修繕5,000万ウォン'}},
    strong:'強い条件',weak:'弱い条件',changes:'結果を変える条件',finalStrong:'A金融構造の低い金融費用',finalWeak:'B金融構造のストレス時CF',finalChanges:'金利 · 主要テナント空室 · 修繕費'
  }
};
