'use client';

import {Fragment} from 'react';
import AnalysisDetailShell from './AnalysisDetailShell';
import {getExitDecision,getExitSection,getExitSections,getExitUi,normalizeExitLocale} from './exit-i18n-data';
import {EXIT_IMAGES,getExitImageAlt} from './exit-images';

const BASE_PATH='/building';
function SentenceText({text}){const value=String(text??'').trim();const sentences=value.match(/[^.!?。！？\n]+[.!?。！？]?/g)?.map(x=>x.trim()).filter(Boolean)||[];return <>{sentences.map((sentence,i)=><Fragment key={`${i}-${sentence}`}>{sentence}{i<sentences.length-1&&<br/>}</Fragment>)}</>}
function CheckChips({items,label}){return <div className="an19-method-check"><small>{label}</small><div>{items.map(x=><span key={x}>{x}</span>)}</div></div>}

export default function ExitPrototypeClient({view,locale='ko'}){
  const lang=normalizeExitLocale(locale); const s=getExitSection(lang,view); if(!s)return null;
  const sections=getExitSections(lang); const decision=getExitDecision(lang); const ui=getExitUi(lang);
  const back=()=>{location.href=`${BASE_PATH}/${lang}/exit`;};
  const nextHref=s.nextId?`${BASE_PATH}/${lang}/exit/${s.nextId}`:`${BASE_PATH}/${lang}/exit`;
  return <div className="analysis-page-v019 mg-management-page exit-decision-page exit-prototype-page">
    <AnalysisDetailShell eyebrow={`${s.num} · ${s.code}`} title={s.name} lead={s.prompt} onBack={back} backLabel="← EXIT HOME">
      <figure className="mg-detail-hero-image exit-detail-hero"><img src={EXIT_IMAGES[s.id]} alt={getExitImageAlt(lang,s.id)||`${s.name} ${ui.guideImage}`} loading="eager" decoding="async"/></figure>
      <section className="an19-block an19-concept mg-rent-detail"><header><small>01 · WHY</small><h2>{s.prompt}</h2></header><div className="an19-longcopy mg-rent-longcopy exit-why-copy"><p>{s.lead}</p>{s.whyDetails.map((text,i)=><p key={i}>{text}</p>)}</div></section>
      <section className="an19-block mg-management-terms"><header><small>02 · CORE</small><h2>{ui.protoCoreTitle}</h2><p>{ui.protoCoreLead}</p></header><div className="an19-terms">{s.core.map(([title,desc],i)=><div key={title}><strong><span className="exit-inline-num">{String(i+1).padStart(2,'0')}</span>{title}</strong><p><SentenceText text={desc}/></p></div>)}</div></section>
      <section className="an19-block an19-method mg-rent-detail"><header><small>03 · METHOD</small><h2>{ui.protoMethodTitle}</h2><p>{ui.protoMethodLead}</p></header><div className="an19-method-list mg-rent-method-list">{s.method.map(([title,desc,checks,caution,done],i)=><article key={title}><div className="an19-method-num">{String(i+1).padStart(2,'0')}</div><section><h3>{title}</h3><div className="mg-rent-step-copy"><p><SentenceText text={desc}/></p></div><CheckChips items={checks} label={ui.check}/><div className="an19-method-caution"><small>{ui.watchOut}</small><p><SentenceText text={caution}/></p></div><div className="exit-method-done"><small>{ui.readyWhen}</small><p><SentenceText text={done}/></p></div></section></article>)}</div></section>
      <section className="an19-block an19-related mg-rent-signals exit-signal-pair"><header><small>04 · REVIEW SIGNALS</small><h2>{ui.protoSignalsTitle}</h2><p>{ui.protoSignalsLead}</p></header><div className="exit-signal-grid"><div><small>REVIEW SIGNAL</small><h3>{ui.reviewSignal}</h3><CheckChips items={s.signals} label={ui.check}/></div><div><small>READY SIGNAL</small><h3>{ui.readySignal}</h3><CheckChips items={s.readySignals} label={ui.check}/></div></div></section>
      <section className="an19-block an19-practice mg-rent-practice mg-detail-practice"><header><small>05 · PRACTICE CASES</small><h2>{ui.protoCasesTitle}</h2><p>{ui.protoCasesLead}</p></header><div className="an19-method-list mg-rent-case-list exit-case-detail-list">{s.cases.map((item,i)=><article key={item.label}><div className="an19-method-num">{String(i+1).padStart(2,'0')}</div><section><small>{item.label}</small><h3>{item.title}</h3><div className="mg-rent-step-copy"><p><SentenceText text={item.situation}/></p></div><div className="exit-case-grid"><div><small>{ui.observe}</small><p><SentenceText text={item.observe}/></p></div><div><small>{ui.decisionPoint}</small><p><SentenceText text={item.judge}/></p></div><div><small>{ui.nextCheck}</small><p><SentenceText text={item.next}/></p></div></div></section></article>)}</div></section>
      <section className="an19-block mg-management-terms exit-self-questions"><header><small>06 · SELF CHECK</small><h2>{ui.protoQuestionsTitle}</h2><p>{ui.protoQuestionsLead}</p></header><div className="an19-terms">{s.questions.map((item,i)=><div key={item.q}><strong><span className="exit-inline-num">{String(i+1).padStart(2,'0')}</span>{item.q}</strong><p>{item.why}</p><div className="exit-question-next"><small>{ui.ifNot}</small><p><SentenceText text={item.next}/></p></div></div>)}</div></section>
      <section className="an19-block an19-related exit-professional-check"><header><small>07 · PROFESSIONAL CHECK</small><h2>{ui.professionalTitle}</h2><p>{ui.professionalProtoLead}</p></header><div className="exit-professional-list">{s.experts.map((item,i)=><article key={item.topic}><div className="exit-professional-num">{String(i+1).padStart(2,'0')}</div><section><h3>{item.topic}</h3><p className="exit-professional-intro"><SentenceText text={item.intro}/></p><div className="exit-professional-grid"><div><small>{ui.whatToCheck}</small><strong>{item.check}</strong></div><div><small>{ui.checkWhen}</small><ul>{item.when.map(x=><li key={x}>{x}</li>)}</ul></div><div><small>{ui.prepare}</small><ul>{item.prepare.map(x=><li key={x}>{x}</li>)}</ul></div><div><small>{ui.confirmWith}</small><strong>{item.confirm}</strong></div></div><div className="exit-professional-apply"><small>{ui.apply}</small><p><SentenceText text={item.apply}/></p></div></section></article>)}</div><div className="exit-confirmation-status"><small>{ui.confirmationStatus}</small><h3>{s.expertStatus.title}</h3><p><SentenceText text={s.expertStatus.body}/></p><div>{s.expertStatus.items.map(x=><span key={x}>{x}<b>{ui.confirmedCheck}</b></span>)}</div></div></section>
      <section className="an19-block an19-summary"><header><small>08 · SUMMARY</small><h2>{s.name}{ui.summarySuffix}</h2></header><div className="an19-summary-grid exit-summary-grid">{s.summary.map((text,i)=><div key={text}><span>{String(i+1).padStart(2,'0')}</span><strong>{text}</strong></div>)}</div><div className="exit-page-conclusion"><small>FINAL POINT</small><p><SentenceText text={s.conclusion}/></p></div></section>
      <p className="an19-note">{ui.protoDisclaimer}</p>
      <div className="ctj-next"><div><small>{ui.currentStep}</small><strong>{s.num} {s.name}</strong></div><a href={nextHref}><small>{ui.nextStep}</small><strong>{s.nextName}</strong><p>{s.nextPrompt}</p><b>→</b></a></div>
      <nav className="an41-axis-endnav" aria-label={ui.exitNav}><button type="button" className="an41-back-home" onClick={back}><span aria-hidden="true">←</span><strong>EXIT HOME</strong></button><div className="an41-other-head"><small>{ui.exploreNextLabel}</small><h2>{ui.exploreNext}</h2></div><div className="an41-other-grid">{sections.filter(x=>x.id!==s.id).map(item=><a key={item.id} className="an41-other-axis" href={`${BASE_PATH}/${lang}/exit/${item.id}`}><span className="an41-other-num">{item.num}</span><span className="an41-other-copy"><small>{item.code}</small><strong>{item.name}</strong><em>{item.prompt}</em></span><span className="an41-other-arrow" aria-hidden="true">→</span></a>)}<a className="an41-other-axis" href={`${BASE_PATH}/${lang}/exit/decision`}><span className="an41-other-num">01</span><span className="an41-other-copy"><small>{decision.code}</small><strong>{decision.name}</strong><em>{decision.prompt}</em></span><span className="an41-other-arrow" aria-hidden="true">→</span></a></div></nav>
    </AnalysisDetailShell>
  </div>;
}
