'use client';

import {Fragment} from 'react';
import AnalysisDetailShell from './AnalysisDetailShell';
import {getExitDecision,getExitSections,getExitUi,normalizeExitLocale} from './exit-i18n-data';
import {EXIT_IMAGES,getExitImageAlt} from './exit-images';

const BASE_PATH='/building';
function SentenceText({text}){const value=String(text??'').trim();const sentences=value.match(/[^.!?。！？\n]+[.!?。！？]?/g)?.map(x=>x.trim()).filter(Boolean)||[];return <>{sentences.map((sentence,i)=><Fragment key={`${i}-${sentence}`}>{sentence}{i<sentences.length-1&&<br/>}</Fragment>)}</>}
function CheckChips({items,label}){return <div className="an19-method-check"><small>{label}</small><div>{items.map(x=><span key={x}>{x}</span>)}</div></div>}
function MethodList({items,ui}){return <div className="an19-method-list mg-rent-method-list">{items.map((item,i)=><article key={item.title}><div className="an19-method-num">{String(i+1).padStart(2,'0')}</div><section><h3>{item.title}</h3><div className="mg-rent-step-copy">{item.paragraphs.map((p,pi)=><p key={pi}><SentenceText text={p}/></p>)}</div><CheckChips items={item.checks} label={ui.check}/><div className="an19-method-caution"><small>{ui.watchOut}</small><p><SentenceText text={item.caution}/></p></div><div className="exit-method-done"><small>{ui.readyWhen}</small><p><SentenceText text={item.done}/></p></div></section></article>)}</div>}

export default function ExitClient({locale='ko'}){
  const lang=normalizeExitLocale(locale); const s=getExitDecision(lang); const ui=getExitUi(lang); const other=getExitSections(lang);
  const back=()=>{location.href=`${BASE_PATH}/${lang}/exit`;};
  return <div className="analysis-page-v019 mg-management-page exit-decision-page">
    <AnalysisDetailShell eyebrow={`${s.num} · ${s.code}`} title={s.name} lead={s.prompt} onBack={back} backLabel="← EXIT HOME">
      <figure className="mg-detail-hero-image exit-detail-hero"><img src={EXIT_IMAGES.decision} alt={getExitImageAlt(lang,'decision')} loading="eager" decoding="async"/></figure>
      <section className="an19-block an19-concept mg-rent-detail"><header><small>01 · WHY EXIT</small><h2>{s.why.title}</h2></header><div className="an19-longcopy mg-rent-longcopy exit-why-copy">{s.why.body.map((text,i)=><p key={i}>{text}</p>)}</div><div className="an19-terms exit-three-reasons">{s.why.groups.map(([num,title,desc])=><div key={num}><span className="exit-inline-num">{num}</span><h3>{title}</h3><p>{desc}</p></div>)}</div></section>
      <section className="an19-block mg-management-terms"><header><small>02 · SIX DECISION FACTORS</small><h2>{ui.decisionCoreTitle}</h2><p>{ui.decisionCoreLead}</p></header><div className="an19-terms">{s.core.map((item,i)=><div key={item.title}><strong><span className="exit-inline-num">{String(i+1).padStart(2,'0')}</span>{item.title}</strong><p><SentenceText text={item.desc}/></p><div className="mg-rent-interpret"><small>{ui.key}</small><p><SentenceText text={item.key}/></p></div></div>)}</div></section>
      <section className="an19-block an19-method mg-rent-detail"><header><small>03 · DECISION METHOD</small><h2>{ui.decisionMethodTitle}</h2><p>{ui.decisionMethodLead}</p></header><div className="an19-method-flow" aria-label={ui.decisionFlowAria}>{s.method.map((item,i)=><span key={item.title}><b>{String(i+1).padStart(2,'0')}</b>{item.title}</span>)}</div><MethodList items={s.method} ui={ui}/></section>
      <section className="an19-block an19-related mg-rent-signals exit-signal-pair"><header><small>04 · REVIEW SIGNALS</small><h2>{ui.decisionSignalsTitle}</h2><p>{ui.decisionSignalsLead}</p></header><div className="exit-signal-grid"><div><small>REVIEW SIGNAL</small><h3>{ui.reviewSignal}</h3><CheckChips items={s.reviewSignals.checks} label={ui.check}/><div className="mg-rent-interpret"><small>{ui.interpret}</small><p>{s.reviewSignals.interpret}</p></div></div><div><small>READY / HOLD SIGNAL</small><h3>{ui.holdSignal}</h3><CheckChips items={s.holdSignals.checks} label={ui.check}/><div className="mg-rent-interpret"><small>{ui.interpret}</small><p>{s.holdSignals.interpret}</p></div></div></div></section>
      <section className="an19-block an19-practice mg-rent-practice mg-detail-practice"><header><small>05 · PRACTICE CASES</small><h2>{ui.decisionCasesTitle}</h2><p>{ui.decisionCasesLead}</p></header><div className="an19-method-list mg-rent-case-list">{s.cases.map((item,i)=><article key={item.title}><div className="an19-method-num">{String(i+1).padStart(2,'0')}</div><section><h3>{item.title}</h3><div className="mg-rent-step-copy">{item.desc.map((p,pi)=><p key={pi}><SentenceText text={p}/></p>)}</div><CheckChips items={item.checks} label={ui.check}/><div className="mg-rent-case-note"><small>{ui.decisionPoint}</small><p><SentenceText text={item.judge}/></p></div></section></article>)}</div></section>
      <section className="an19-block mg-management-terms exit-self-questions"><header><small>06 · SELF CHECK</small><h2>{ui.decisionQuestionsTitle}</h2><p>{ui.decisionQuestionsLead}</p></header><div className="an19-terms">{s.questions.map(([num,q,why,next])=><div key={num}><strong><span className="exit-inline-num">{num}</span>{q}</strong><p><SentenceText text={why}/></p><div className="exit-question-next"><small>{ui.ifNot}</small><p><SentenceText text={next}/></p></div></div>)}</div></section>
      <section className="an19-block mg-management-terms"><header><small>07 · COMMON MISTAKES</small><h2>{ui.mistakesTitle}</h2><p>{ui.mistakesLead}</p></header><div className="an19-terms">{s.mistakes.map(([num,title,desc])=><div key={num}><strong><span className="exit-inline-num">{num}</span>{title}</strong><p><SentenceText text={desc}/></p></div>)}</div></section>
      <section className="an19-block an19-related exit-professional-check"><header><small>08 · PROFESSIONAL CHECK</small><h2>{ui.professionalTitle}</h2><p>{ui.professionalDecisionLead}</p></header><div className="exit-professional-list">{s.experts.map((item,i)=><article key={item.topic}><div className="exit-professional-num">{String(i+1).padStart(2,'0')}</div><section><h3>{item.topic}</h3><p className="exit-professional-intro"><SentenceText text={item.intro}/></p><div className="exit-professional-grid"><div><small>{ui.whatToCheck}</small><strong>{item.check}</strong></div><div><small>{ui.checkWhen}</small><ul>{item.when.map(x=><li key={x}>{x}</li>)}</ul></div><div><small>{ui.prepare}</small><ul>{item.prepare.map(x=><li key={x}>{x}</li>)}</ul></div><div><small>{ui.confirmWith}</small><strong>{item.confirm}</strong></div></div><div className="exit-professional-apply"><small>{ui.apply}</small><p><SentenceText text={item.apply}/></p></div></section></article>)}</div><div className="exit-confirmation-status"><small>{ui.confirmationStatus}</small><h3>{s.expertStatus.title}</h3><p><SentenceText text={s.expertStatus.body}/></p><div>{s.expertStatus.items.map(x=><span key={x}>{x}<b>{ui.confirmedCheck}</b></span>)}</div></div></section>
      <section className="an19-block an19-summary"><header><small>09 · SUMMARY</small><h2>{ui.decisionSummaryTitle}</h2></header><div className="an19-summary-grid exit-summary-grid">{s.summary.map(([num,text])=><div key={num}><span>{num}</span><strong>{text}</strong></div>)}</div><div className="exit-final-statement"><strong>{s.final}</strong></div></section>
      <p className="an19-note">{ui.decisionDisclaimer}</p>
      <div className="ctj-next"><div><small>{ui.currentStep}</small><strong>{s.num} {s.name}</strong></div><a href={`${BASE_PATH}/${lang}/exit/readiness`}><small>{ui.nextStep}</small><strong>{other[0].num} {other[0].name}</strong><p>{s.next.body}</p><b>→</b></a></div>
      <nav className="an41-axis-endnav" aria-label={ui.exitNav}><button type="button" className="an41-back-home" onClick={back}><span aria-hidden="true">←</span><strong>EXIT HOME</strong></button><div className="an41-other-head"><small>{ui.exploreNextLabel}</small><h2>{ui.exploreNext}</h2></div><div className="an41-other-grid">{other.map(item=><a key={item.id} className="an41-other-axis" href={`${BASE_PATH}/${lang}/exit/${item.id}`}><span className="an41-other-num">{item.num}</span><span className="an41-other-copy"><small>{item.code}</small><strong>{item.name}</strong></span><span className="an41-other-arrow" aria-hidden="true">→</span></a>)}</div></nav>
    </AnalysisDetailShell>
  </div>;
}
