const serviceBase = {
  self: { image: '/building/assets/service-self.webp', num: '01', icon: 'check' },
  analysis: { image: '/building/assets/service-analysis.webp', num: '02', icon: 'analysis' },
  contract: { image: '/building/assets/service-contract.webp', num: '03', icon: 'contract' },
  management: { image: '/building/assets/service-management.webp', num: '04', icon: 'management' },
  exit: { image: '/building/images/exit/exit-main.webp', num: '05', icon: 'exit' },
};

const makeServices = (items) => Object.entries(items).map(([id, value]) => ({ id, ...serviceBase[id], ...value }));

export const LOCALES = [
  { code: 'ko', label: '한국어' },
  { code: 'en', label: 'English' },
  { code: 'ja', label: '日本語' },
];

export const SITE_COPY = {
  ko: {
    metaTitle: 'FIX BUILDING',
    metaDescription: '건물·상가의 진단, 분석, 계약, 관리, 매각 판단을 단계별로 확인하는 FIX BUILDING.',
    navAria: '서비스 바로가기',
    heroAria: 'FIX BUILDING 히어로',
    flowAria: '서비스 흐름',
    servicesAria: 'FIX BUILDING 서비스',
    guideIntroAria: '사용 가이드 소개',
    guideAria: 'FIX 사이트 활용법',
    heroLine1: '건물을 보기 전부터, 보유하고 나가는 순간까지.',
    heroLine2: '필요한 판단을 직접 확인합니다.',
    heroCta: '서비스 흐름 보기',
    services: makeServices({
      self: { label: '자가진단', desc: '건물을 보기 전에 나부터 확인', alt: '자가진단을 위한 체크리스트 이미지' },
      analysis: { label: '분석', desc: '가격·수익·권리·건물·입지·운영 6축 분석', alt: '건물 데이터를 분석하는 이미지' },
      contract: { label: '계약', desc: '안전한 계약을 위한 핵심 절차', alt: '계약 조건을 확인하는 이미지' },
      management: { label: '관리', desc: '보유 중 가치와 현금흐름 관리', alt: '건물 관리 상태를 확인하는 이미지' },
      exit: { label: 'EXIT', desc: '보유와 매각의 기준을 확인', alt: '상업용 건물을 중심으로 여섯 단계의 EXIT 흐름을 표현한 건축형 이미지' },
    }),
    guideTitle: '건물을 더 잘 판단하는 방법.',
    guideLead: 'FIX는 건물과 관련된 판단을 단계별로 직접 확인할 수 있도록 구성되어 있습니다.',
    checkLabel: '이 단계에서 확인할 것',
    guideItems: [
      { num: '01', phase: 'START', title: '자가진단', checks: ['현재 조건','검토 목적','주요 부담요소'], body: '건물을 검토하기 전에 현재 상황과 목적을 먼저 정리합니다. 보유 목적, 검토 조건, 예상되는 부담 등을 확인하면 이후 분석에서 어떤 항목을 우선적으로 살펴봐야 하는지 판단하기 쉬워집니다.' },
      { num: '02', phase: 'CHECK', title: '분석', checks: ['PRICE','INCOME','RIGHTS','BUILDING','LOCATION','OPERATION'], body: '건물을 볼 때는 호가나 표면수익률 하나로 결론내리지 않습니다. 가격·수익·권리·건물·입지·운영을 순서대로 확인하고, 실제 매입 전 무엇을 어떤 기준으로 봐야 하는지 연결해 봅니다.' },
      { num: '03', phase: 'DECIDE', title: '계약', checks: ['계약 조건','권리관계','주요 확인사항'], body: '계약 단계에서는 가격뿐 아니라 계약 조건과 권리관계, 확인해야 할 사항을 다시 점검하는 것이 중요합니다. 계약 전에 확인할 항목을 순서대로 검토하면 중요한 조건을 놓칠 가능성을 줄일 수 있습니다.' },
      { num: '04', phase: 'HOLD', title: '관리', checks: ['가치 변화','현금흐름','관리 상태'], body: '보유를 시작한 이후에는 매입 당시의 판단만 유지하는 것이 아니라 건물의 가치와 현금흐름, 유지관리 상태를 계속 확인해야 합니다. 시간이 지나면서 달라지는 조건을 다시 비교하면 현재 보유 상황을 점검하는 데 도움이 됩니다.' },
      { num: '05', phase: 'EXIT', title: '매각', checks: ['현재 가치','보유 조건','매각 조건'], body: '매각을 검토할 때는 현재 가격만 보는 것이 아니라 계속 보유했을 때와 매각했을 때의 조건을 비교하는 것이 중요합니다. 현재 상황과 향후 예상되는 조건을 함께 살펴보고 의사결정 기준을 정리합니다.' },
    ],
    footer: { privacy: '개인정보처리방침', terms: '이용약관', contact: '문의하기' },
  },
  en: {
    metaTitle: 'FIX BUILDING | Property Decision Guide',
    metaDescription: 'A practical framework for evaluating, buying, managing and exiting building investments with clearer decision criteria.',
    navAria: 'Service navigation',
    heroAria: 'FIX BUILDING hero',
    flowAria: 'Service process',
    servicesAria: 'FIX BUILDING services',
    guideIntroAria: 'How to use FIX BUILDING',
    guideAria: 'FIX BUILDING guide',
    heroLine1: 'From the first look at a property to the day you exit.',
    heroLine2: 'Review the decisions that matter, step by step.',
    heroCta: 'Explore the process',
    services: makeServices({
      self: { label: 'SELF CHECK', desc: 'Start with your own goals and constraints', alt: 'Property self-check checklist' },
      analysis: { label: 'ANALYSIS', desc: 'Analyze price, income, rights, building, location and operation', alt: 'Professionals reviewing property data' },
      contract: { label: 'CONTRACT', desc: 'Check the essentials before you sign', alt: 'Professional reviewing contract terms' },
      management: { label: 'MANAGEMENT', desc: 'Track value and cash flow while you hold', alt: 'Building management review' },
      exit: { label: 'EXIT', desc: 'Set clear criteria for holding or selling', alt: 'Architectural visualization of a six-stage commercial property exit journey around one building' },
    }),
    guideTitle: 'A clearer way to evaluate a building.',
    guideLead: 'FIX organizes the key decisions around a property into a practical sequence you can review for yourself.',
    checkLabel: 'What to review',
    guideItems: [
      { num: '01', phase: 'START', title: 'Self Check', checks: ['Current position','Objective','Key constraints'], body: 'Before evaluating a property, clarify where you stand and what you are trying to achieve. Defining your objective, conditions and likely constraints makes it easier to decide what deserves the most attention later.' },
      { num: '02', phase: 'CHECK', title: 'Analysis', checks: ['PRICE','INCOME','RIGHTS','BUILDING','LOCATION','OPERATION'], body: 'Review price, income, rights, building condition, location and operation in sequence so you can see what to check before deciding on a property.' },
      { num: '03', phase: 'DECIDE', title: 'Contract', checks: ['Contract terms','Legal rights','Critical checks'], body: 'At the contract stage, review more than the price. Terms, rights and key confirmations should be checked again in a clear order before signing to reduce the chance of overlooking an important condition.' },
      { num: '04', phase: 'HOLD', title: 'Management', checks: ['Value changes','Cash flow','Property condition'], body: 'Once you own the property, the original purchase decision is no longer enough. Keep reviewing value, cash flow and maintenance conditions as they change so the current holding position remains visible.' },
      { num: '05', phase: 'EXIT', title: 'Exit', checks: ['Current value','Holding case','Sale conditions'], body: 'An exit decision should compare the case for continuing to hold with the case for selling. Review the current position and likely future conditions together, then define the criteria that will guide the decision.' },
    ],
    footer: { privacy: 'Privacy Policy', terms: 'Terms of Use', contact: 'Contact' },
  },
  ja: {
    metaTitle: 'FIX BUILDING | 不動産判断ガイド',
    metaDescription: '建物の検討から分析、契約、保有管理、売却まで、判断すべきポイントを段階ごとに整理するFIX BUILDING。',
    navAria: 'サービスナビゲーション',
    heroAria: 'FIX BUILDING メインビジュアル',
    flowAria: 'サービスの流れ',
    servicesAria: 'FIX BUILDING サービス',
    guideIntroAria: '利用ガイド',
    guideAria: 'FIX BUILDING 活用ガイド',
    heroLine1: '物件を探し始める前から、保有し、手放すその時まで。',
    heroLine2: '必要な判断を、一つずつ自分で確かめます。',
    heroCta: 'サービスの流れを見る',
    services: makeServices({
      self: { label: '自己診断', desc: '物件を見る前に、自分の条件を確認', alt: '自己診断用チェックリストのイメージ' },
      analysis: { label: '分析', desc: '価格・収益・権利・建物・立地・運営の6軸で分析', alt: '不動産データを分析するイメージ' },
      contract: { label: '契約', desc: '契約前に重要ポイントを確認', alt: '契約条件を確認するイメージ' },
      management: { label: '管理', desc: '保有中の価値と収支を継続管理', alt: '建物の管理状況を確認するイメージ' },
      exit: { label: 'EXIT', desc: '保有継続と売却の判断基準を確認', alt: '1棟の商業ビルを中心に6段階のEXITプロセスを表した建築イメージ' },
    }),
    guideTitle: '建物を、より的確に判断するために。',
    guideLead: 'FIXは、建物に関する判断を段階ごとに整理し、自分で確認できるように構成しています。',
    checkLabel: 'この段階で確認すること',
    guideItems: [
      { num: '01', phase: 'START', title: '自己診断', checks: ['現在の条件','検討目的','主な負担要因'], body: '物件を検討する前に、まず現在の状況と目的を整理します。保有目的や検討条件、想定される負担を確認しておくことで、その後の分析で何を優先して見るべきかが明確になります。' },
      { num: '02', phase: 'CHECK', title: '分析', checks: ['PRICE','INCOME','RIGHTS','BUILDING','LOCATION','OPERATION'], body: '価格・収益・権利・建物状態・立地・運営を順番に確認し、購入前に何をどの基準で見るかを整理します。' },
      { num: '03', phase: 'DECIDE', title: '契約', checks: ['契約条件','権利関係','重要確認事項'], body: '契約段階では、価格だけでなく契約条件や権利関係、事前に確認すべき事項を改めて点検します。確認項目を順番に整理することで、重要な条件の見落としを減らせます。' },
      { num: '04', phase: 'HOLD', title: '管理', checks: ['価値の変化','キャッシュフロー','管理状況'], body: '保有を始めた後は、購入時の判断だけに頼らず、建物の価値やキャッシュフロー、維持管理の状態を継続して確認します。条件の変化を定期的に見直すことが、現在の保有状況を把握する手掛かりになります。' },
      { num: '05', phase: 'EXIT', title: '売却', checks: ['現在価値','保有条件','売却条件'], body: '売却を検討するときは、現在価格だけでなく、保有を続ける場合と売却する場合の条件を比較します。現在の状況と今後想定される条件を合わせて確認し、判断基準を整理します。' },
    ],
    footer: { privacy: 'プライバシーポリシー', terms: '利用規約', contact: 'お問い合わせ' },
  },
};
